BITS 16


        SCREEN_WIDTH equ 320
        SCREEN_HEIGHT equ 200
        VIDEO_BUFFER equ 0xA000
        BG_COLOR equ 0x0B
        SCREEN_SIZE equ (SCREEN_HEIGHT * SCREEN_WIDTH)

        PIPE_COLOR equ 0x02
        PIPE_HEIGHT equ 200
        PIPE_WIDTH equ 20
        PIPE_HOLE_SIZE equ 40
        PIPE_HOLE_RANGE equ PIPE_HEIGHT
;; PRNG Constants
        RANDOM_SEED equ 12345
        RANDOM_MODULUS equ PIPE_HEIGHT
        RANDOM_MULTIPLIER equ 1103515245
        RANDOM_INCREMENT equ 12345
